### ISSUE TITLE
RFE: Dynamic manipulation of Command hierarchy

### ISSUE THREAD

**Issue by djerius** [sbakker/perl-Term-CLI#16]
I've run into a situation where dynamic reloading of the command structure would be helpful.

In my application there are some dangerous commands that should not be available unless you've sworn an oath that you know what you're doing.  One of them is `admin db nuke`.  At the moment I control this from the command line by turning on those commands only if the `--admin` flag is set (and the user is authorized to have access to those commands).  However, this can lead to dangerous situations where the user always runs with `--admin` because it's too much of a pain to exit and re-enter the application.

With dynamic reloading, the user could issue a command to turn on admin mode and the code would then rebuild the command list, exposing the admin commands.  Turning off that mode would rebuild the command list without those commands.

The first step would be adding a `delete_command` method to `Term::CLI::Role::CommandSet`.  Next would be investigate if the help system needs tweaking; I'm not sure how much state it caches.

I don't know if a top-level "rebuild command hierarchy" method is possible, as that might bake in policies ono how to decide which command nodes to add or delete, which may be very application dependent.

**Comment by sbakker** [comment]
It's possilbe that a `delete_command` is all we need. The Help system caches no state, so that should not make a difference. I'll have a look.

**Comment by sbakker** [comment]
Hi, it's been a while! I just merged some work into `dev` that implements a `delete_command`, see the `examples/dynamic_commands.pl` script.

There's been quite some other work as well:

 * The `commands` argument in the Command anc CLI constructors now takes a CodeRef as well. Unlike the Enum values list, this CodeRef is called once at most. This can help reduce startup time when used in deeper layers of the command hierarchy.
 * The Command and Enum lists are now internally sorted, so that matching can be optimised for large lists (incorporate binary searching for larg-ish lists). See `examples/bit_enum.pl`.
 * An additional attribute `state` is available in Command and CLI objects to keep local/global state in hashes, see `examples/state_demo.pl`.

**Comment by sbakker** [comment]
0.055001 released to CPAN today.
