### ISSUE TITLE
RFE:  argument completion based on preceding argument values

### ISSUE THREAD

**Issue by djerius** [sbakker/perl-Term-CLI#17]
Imagine a command which takes arguments

    continent country city street number

I'd like  be able to use values for previously provided arguments to customize completions.  For example, if the user enters "Africa" for the continent, completions for "Country" would only provide results for "Africa", etc.

As far as I can tell, the current interface for argument processing doesn't pass context about the state of processing the command line to the `Term::CLI::Argument` completion methods.

**Comment by sbakker** [comment]
This one is probably not too difficult, especially since the `Term::CLI::Command`'s complete function already receives the command path. Doing this for arguments should not be too much of a stretch. It will mean a breaking change in the current completion logic, but I think that is limited to within the `Term::CLI` modules themselves.

**Comment by sbakker** [comment]
I created a branch off of `dev`, called `feature/completion-context` that implements a way to do context-sensitive completion. It introduces a second argument to `complete`, a HashRef with "state" information that includes the preceding words on the command line (in the `$state->{processed}` ArrayRef) and a collection of options seen so far (in `$state->{options}` HashRef).

I also included a dumb demo/test script in `examples/context_sensitive_completion` to test it.

I'm not going to merge yet, as I also want to add a similar state argument to the argument validation.

Further changes:

 * Minor bug fix in Tutorial code.
 * Add tutorial entry for dynamic Enum values.
 * Enum's `_fetch_values` has been promoted to a public `values` method.
 * Addition of caching option for Enum value list (in case you want to load the list on-demand, but only once).
 * Addition of a `Util` module that takes some common code and puts it in one place (option parsing, string prefix matching).
 * Small enhancement of Boolean completion (completions now match case of the partial text).
 * Create ReadLine object that uses *STDIN* and *STDOUT* by default, instead of letting (Gnu) ReadLine find and open the TTY separately. This ensures that `perl readline_app < input_file` will actually read input from `input_file`, while also making sure that whatever encoding you have on the standard file handles (`use open qw(:std :utf8)`) will also be applied to the ReadLine I/O. This will ensure that Estonians can write "tõsi" for "true" and Macedonians can write "лажни" for "false".
 * Various POD fixes.

**Comment by djerius** [comment]
> I created a branch off of dev, called feature/completion-context

Cool!

> Addition of caching option for Enum value list (in case you want to load the list on-demand, but only once).

I've settled on this paradigm using `state` variables for accomplishing this sort of thing, 

`sub value_list { state @values = do { ... }; }`

or, for earlier Perl's where `state` only takes a scalar:

`sub value_list { state $values = do { ... }; @$values }`

Nice thing is that it doesn't require upstream support for caching

**Comment by sbakker** [comment]
True, for most cases a `state` variable works well enough. There may be cases, though, where you want to invalidate that cache, so in that case the `value_list` CodeRef would have to track some external state variable, which may get messy. For this purpose the built-in caching may be handy. YMMV, TMTOWTDI ;-)
